//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Total.DealerCom.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Total.DealerCom.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select at least one item.
        /// </summary>
        internal static string AtLeastOneItemSelectionMessage {
            get {
                return ResourceManager.GetString("AtLeastOneItemSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a comment..
        /// </summary>
        internal static string CommentsMandatoryMessage {
            get {
                return ResourceManager.GetString("CommentsMandatoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New questionnaire must be saved first before questions can be added to it. Please click save button..
        /// </summary>
        internal static string Edit_BtnAddClick_New_questionnaire_must_be_saved_first_before_questions_can_be_added_to_it__Please_click_save_button_ {
            get {
                return ResourceManager.GetString("Edit_BtnAddClick_New_questionnaire_must_be_saved_first_before_questions_can_be_ad" +
                        "ded_to_it__Please_click_save_button_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be supplied..
        /// </summary>
        internal static string Edit_BtnOkClick_Date_must_be_supplied_ {
            get {
                return ResourceManager.GetString("Edit_BtnOkClick_Date_must_be_supplied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire {0} updated..
        /// </summary>
        internal static string Edit_BtnOkClick_Questionnaire_ {
            get {
                return ResourceManager.GetString("Edit_BtnOkClick_Questionnaire_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be supplied..
        /// </summary>
        internal static string Edit_BtnOkClick_Title_must_be_supplied_ {
            get {
                return ResourceManager.GetString("Edit_BtnOkClick_Title_must_be_supplied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire must first be saved before questions can be added to it. Click the save button to update or add the questionnaire..
        /// </summary>
        internal static string Edit_BtnUseClick_Questionnaire_must_first_be_saved_before_questions_can_be_added_to_it__Click_the_save_button_to_update_or_add_the_questionnaire_ {
            get {
                return ResourceManager.GetString("Edit_BtnUseClick_Questionnaire_must_first_be_saved_before_questions_can_be_added_" +
                        "to_it__Click_the_save_button_to_update_or_add_the_questionnaire_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Questionnaire.
        /// </summary>
        internal static string Edit_Page_Load_Edit_Questionnaire {
            get {
                return ResourceManager.GetString("Edit_Page_Load_Edit_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Edit_PopulateQuestionnaire_Group {
            get {
                return ResourceManager.GetString("Edit_PopulateQuestionnaire_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questionnaires have been selected..
        /// </summary>
        internal static string Edit_TxtDeleteClick_No_questionnaires_have_been_selected_ {
            get {
                return ResourceManager.GetString("Edit_TxtDeleteClick_No_questionnaires_have_been_selected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to mark all items as either Approved/Rejected.
        /// </summary>
        internal static string EditGeneralChange_BtnDataApproveClick_You_have_to_mark_all_items_as_either_Approved_Rejected {
            get {
                return ResourceManager.GetString("EditGeneralChange_BtnDataApproveClick_You_have_to_mark_all_items_as_either_Approv" +
                        "ed_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to supply a comment when rejecting a request..
        /// </summary>
        internal static string EditGeneralChange_BtnDataRejectClick_You_have_to_supply_a_comment_when_rejecting_a_request_ {
            get {
                return ResourceManager.GetString("EditGeneralChange_BtnDataRejectClick_You_have_to_supply_a_comment_when_rejecting_" +
                        "a_request_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select at least one item from every group..
        /// </summary>
        internal static string ItemSelectionCriteriaMessage {
            get {
                return ResourceManager.GetString("ItemSelectionCriteriaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Questionnaire.
        /// </summary>
        internal static string Maintain_Page_Load_Maintain_Questionnaire {
            get {
                return ResourceManager.GetString("Maintain_Page_Load_Maintain_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer type must be supplied..
        /// </summary>
        internal static string OptionEdit_BtnOkClick_Answer_type_must_be_supplied_ {
            get {
                return ResourceManager.GetString("OptionEdit_BtnOkClick_Answer_type_must_be_supplied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question saved. Reminder: Please remember to supply &apos;answer options&apos; to your question below..
        /// </summary>
        internal static string OptionEdit_BtnOkClick_Question_saved__Reminder__Please_remember_to_supply__answer_options__to_your_question_below_ {
            get {
                return ResourceManager.GetString("OptionEdit_BtnOkClick_Question_saved__Reminder__Please_remember_to_supply__answer" +
                        "_options__to_your_question_below_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section must be supplied..
        /// </summary>
        internal static string OptionEdit_BtnOkClick_Section_must_be_supplied_ {
            get {
                return ResourceManager.GetString("OptionEdit_BtnOkClick_Section_must_be_supplied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option value cannot be empty.
        /// </summary>
        internal static string OptionEdit_GrdResultsRowCommand_Option_value_cannot_be_empty {
            get {
                return ResourceManager.GetString("OptionEdit_GrdResultsRowCommand_Option_value_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        internal static string OptionEdit_Page_Load_Edit_Question {
            get {
                return ResourceManager.GetString("OptionEdit_Page_Load_Edit_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a Recipe Name..
        /// </summary>
        internal static string RecipeNameRequired {
            get {
                return ResourceManager.GetString("RecipeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report available to download.
        /// </summary>
        internal static string Reports_Download_No_report_available_to_download {
            get {
                return ResourceManager.GetString("Reports_Download_No_report_available_to_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Questionnaire is selected.
        /// </summary>
        internal static string ReportSearch_BtnReportClick_No_Questionnaire_is_selected {
            get {
                return ResourceManager.GetString("ReportSearch_BtnReportClick_No_Questionnaire_is_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections were selected..
        /// </summary>
        internal static string RepSection_BtnCreateClick_No_sections_were_selected_ {
            get {
                return ResourceManager.GetString("RepSection_BtnCreateClick_No_sections_were_selected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From-date cannot be later than to-date..
        /// </summary>
        internal static string Search_BindData_From_date_cannot_be_later_than_to_date_ {
            get {
                return ResourceManager.GetString("Search_BindData_From_date_cannot_be_later_than_to_date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From-date cannot be later than to-date..
        /// </summary>
        internal static string SearchGeneralChanges_BindData_From_date_cannot_be_later_than_to_date_ {
            get {
                return ResourceManager.GetString("SearchGeneralChanges_BindData_From_date_cannot_be_later_than_to_date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province must be supplied..
        /// </summary>
        internal static string SearchGeneralChanges_BindData_province_must_be_supplied_ {
            get {
                return ResourceManager.GetString("SearchGeneralChanges_BindData_province_must_be_supplied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Changes archived.
        /// </summary>
        internal static string SearchGeneralChanges_BtnArchiveClick_General_Changes_archived {
            get {
                return ResourceManager.GetString("SearchGeneralChanges_BtnArchiveClick_General_Changes_archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From-date cannot be later than to-date..
        /// </summary>
        internal static string SearchRecipes_BindData_From_date_cannot_be_later_than_to_date_ {
            get {
                return ResourceManager.GetString("SearchRecipes_BindData_From_date_cannot_be_later_than_to_date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes archived.
        /// </summary>
        internal static string SearchRecipes_BtnArchiveClick_Recipes_archived {
            get {
                return ResourceManager.GetString("SearchRecipes_BtnArchiveClick_Recipes_archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string View_BuildQuestionnaire_Partner {
            get {
                return ResourceManager.GetString("View_BuildQuestionnaire_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string View_BuildQuestionnaire_Self {
            get {
                return ResourceManager.GetString("View_BuildQuestionnaire_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Station / Employee Name.
        /// </summary>
        internal static string View_BuildQuestionnaire_Service_Station___Employee_Name {
            get {
                return ResourceManager.GetString("View_BuildQuestionnaire_Service_Station___Employee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Station / Employee No.
        /// </summary>
        internal static string View_BuildQuestionnaire_Service_Station___Employee_No {
            get {
                return ResourceManager.GetString("View_BuildQuestionnaire_Service_Station___Employee_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire Response.
        /// </summary>
        internal static string View_Page_Load_Questionnaire_Response {
            get {
                return ResourceManager.GetString("View_Page_Load_Questionnaire_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all mandatory fields marked with an asterix (*).
        /// </summary>
        internal static string ViewQuestionnaire_BtnSubmitClick_Please_complete_all_mandatory_fields_marked_with_an_asterix____ {
            get {
                return ResourceManager.GetString("ViewQuestionnaire_BtnSubmitClick_Please_complete_all_mandatory_fields_marked_with" +
                        "_an_asterix____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string ViewQuestionnaire_BuildQuestionnaire__ {
            get {
                return ResourceManager.GetString("ViewQuestionnaire_BuildQuestionnaire__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string ViewQuestionnaire_BuildQuestionnaire_Self {
            get {
                return ResourceManager.GetString("ViewQuestionnaire_BuildQuestionnaire_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: You have already answered this questionnaire. Answering it again will replace your previous answers..
        /// </summary>
        internal static string ViewQuestionnaire_CheckIfCompleted_Warning__You_have_already_answered_this_questionnaire__Answering_it_again_will_replace_your_previous_answers_ {
            get {
                return ResourceManager.GetString("ViewQuestionnaire_CheckIfCompleted_Warning__You_have_already_answered_this_questi" +
                        "onnaire__Answering_it_again_will_replace_your_previous_answers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire View.
        /// </summary>
        internal static string ViewQuestionnaire_Page_Load_Questionnaire_View {
            get {
                return ResourceManager.GetString("ViewQuestionnaire_Page_Load_Questionnaire_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string ViewQuestionnaireTemplate_Page_Load__ {
            get {
                return ResourceManager.GetString("ViewQuestionnaireTemplate_Page_Load__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string ViewQuestionnaireTemplate_Page_Load_Partner {
            get {
                return ResourceManager.GetString("ViewQuestionnaireTemplate_Page_Load_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string ViewQuestionnaireTemplate_Page_Load_Self {
            get {
                return ResourceManager.GetString("ViewQuestionnaireTemplate_Page_Load_Self", resourceCulture);
            }
        }
    }
}
